name: Node.js_Pipeline_Example/main
on:
  workflow_dispatch:
env:
  OWNER: ncalteen-migrations
  REPO: gai-node-example
jobs:
  Check_Node:
    name: Check Node
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0-alpine
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-u root:root"
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: node --version
  Build:
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0-alpine
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-u root:root"
    needs: Check_Node
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # 'retry' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: sh
      shell: bash
      run: npm ci
  Test:
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0-alpine
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-u root:root"
    needs: Build
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: npm test
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.7.0
      if: always()
      with:
        junit_files: reports/**/*.xml
  Generate_Cucumber_Reports:
    name: Generate Cucumber Reports
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0-alpine
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-u root:root"
    needs: Test
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: npx cucumber-js --config ./cucumber.json
    - name: Cucumber
      uses: deblockt/cucumber-report-annotations-action@v1.11
      with:
        access-token: "${{ secrets.GITHUB_TOKEN }}"
        path: "**/cucumber-report.json"
  Publish:
    runs-on: ubuntu-latest
    container:
      image: node:18.16.0-alpine
#       # This item has no matching transformer
#       docker:
#         key: args
#         value:
#           isLiteral: true
#           value: "-u root:root"
    needs: Generate_Cucumber_Reports
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Publishing to @${{ env.OWNER }}/${{ env.REPO }}
    - name: sh
      shell: bash
      run: npm publish --registry https://npm.pkg.github.com/
