name: Node.js Pipeline Example

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  OWNER: ncalteen-migrations
  REPO: gai-node-example

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    container: node:18.16.0-alpine

    permissions:
      contents: read
      packages: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ncalteen-migrations'

      - name: Node Version
        shell: sh
        run: node --version

      - name: NPM CI
        shell: sh
        run: npm ci

      - name: NPM Test
        shell: sh
        run: npm test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        if: always()
        with:
          junit_files: reports/**/*.xml

      - name: Generate Cucumber Reports
        shell: sh
        run: npx cucumber-js --config ./cucumber.json

      - name: Add Cucumber Report Annotations
        uses: deblockt/cucumber-report-annotations-action@v1.11
        with:
          access-token: '${{ secrets.GITHUB_TOKEN }}'
          path: '**/cucumber-report.json'

      - name: NPM Publish
        shell: sh
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
